/**
 * Regenerates the BSTS trademark lockup inside og-src.html from the canonical
 * identity source (src/components/brand/bsts-lockup.json).
 *
 * og-src.html is a static page rendered outside Next/React (see
 * scripts/render-og.mjs), so it cannot import <BstsLockup />. Rather than
 * hand-copying the path data — which is what let the share card drift from
 * the site in the past — the markup between the marker comments below is
 * GENERATED from the same JSON the React component reads. There is exactly
 * one copy of the glyph and corner geometry in this repository.
 *
 * Run after scripts/build-lockup-geometry.mjs, then re-render the card:
 *   node scripts/build-lockup-geometry.mjs
 *   node scripts/build-og-src.mjs
 *   node scripts/render-og.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const lockup = JSON.parse(
  readFileSync(resolve(ROOT, "src/components/brand/bsts-lockup.json"), "utf8"),
);

const START = "<!-- BSTS-LOCKUP:START — generated by scripts/build-og-src.mjs, do not edit -->";
const END = "<!-- BSTS-LOCKUP:END -->";

const symbols = Object.entries(lockup.glyphs)
  .map(
    ([id, layers]) =>
      `        <symbol id="og-bsts-${id}" overflow="visible">\n` +
      layers.map((p) => `          <path d="${p.d}" fill="${p.fill}"/>`).join("\n") +
      `\n        </symbol>`,
  )
  .join("\n");

const uses = lockup.letters
  .map((id, i) => `      <use href="#og-bsts-${id}" x="${lockup.letterX[i]}"/>`)
  .join("\n");

const svg = `    <svg viewBox="${lockup.viewBox}" preserveAspectRatio="xMidYMid meet">
      <defs>
${symbols}
      </defs>
${uses}
      <path d="${lockup.corners.lowerLeft}" fill="${lockup.colors.cyan}"/>
      <path d="${lockup.corners.upperRight}" fill="${lockup.colors.cyan}"/>
    </svg>`;

const block = `${START}\n${svg}\n    ${END}`;

const file = resolve(ROOT, "og-src.html");
let html = readFileSync(file, "utf8");

if (html.includes(START)) {
  const re = new RegExp(
    START.replace(/[.*+?^${}()|[\]\\—]/g, "\\$&") + "[\\s\\S]*?" + END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"),
  );
  html = html.replace(re, block);
} else {
  // First run: swap out the previously hand-copied <svg> block.
  const re = /<svg viewBox="[^"]*">[\s\S]*?<\/svg>\s*(?=<\/div>)/;
  if (!re.test(html)) throw new Error("could not locate the existing lockup <svg> in og-src.html");
  html = html.replace(re, block + "\n  ");
}

writeFileSync(file, html);
console.log("og-src.html lockup regenerated from bsts-lockup.json");
console.log("  viewBox", lockup.viewBox, " aspect", lockup.aspect);
